Add type-checking support for SQLModel types.
igorbenav/fastcrud pull request #112
Opened 2024-06-27 23:37 UTC by kdcokenny

# Pull Request Template for FastCRUD

## Description
Please provide a clear and concise description of what your pull request is about.

## Changes
Briefly list the changes you've made. If applicable, also link any relevant issues or pull requests.

## Tests
Describe the tests you added or modified to cover your changes, if applicable.

## Checklist
- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have added tests that cover my changes (if applicable).
- [ ] All new and existing tests passed.

## Additional Notes
Include any additional information that you think is important for reviewers to know.

2024-06-28 00:18 UTC, igorbenav requested changes
This will not work if sqlmodel is not installed. Since it's an optional dependency, it should check if sqlmodel is installed and also work if it's not installed

2024-06-28 00:25 UTC, kdcokenny commented
I'll just leave this here for whoever wants to implement it then. Just needed this for my project.

2024-06-28 10:02 UTC, JakNowy commented
Could we just add sqlmodel as regular dependency then? I think that's de facto the suggested library for fastcrud.

2024-06-28 15:10 UTC, kdcokenny commented
Yeah I did a bit of research into this and the only way I see that we could truly allow it to be optional is to use the `Any` type and put `from sqlmodel import SQLModel` in a try except block. If this is an acceptable approach we could do it, but I cannot find any other workaround for this.

2024-06-28 16:02 UTC, kdcokenny commented
So I did make the `Any` changes above. I also tried adding in run-time validation with:
```python
...
    if not isinstance(model, DeclarativeBase):
        try:
            from sqlmodel.main import SQLModel, SQLModelMetaclass
            if not isinstance(model, Union[SQLModel, SQLModelMetaclass]):
                raise ValueError(
                    f"Invalid model type. Expected SQLAlchemy DeclarativeBase or SQLModel, "
                    f"but got {type(model).__name__}. "
                    f"Please ensure you're using a valid SQLAlchemy or SQLModel model."
                )
        except ImportError:
            raise ImportError(
                f"Invalid model type. Expected SQLAlchemy DeclarativeBase, but got {type(model).__name__}. "
                f"To use SQLModel, ensure you have installed the 'sqlmodel' package. "
                f"You can install it using 'pip install sqlmodel' or 'poetry add sqlmodel'."
            )
```

However, it kept failing tests with random model types which I could manually check for, but am not familiar enough with these libraries to confidently say that would not lead to massive unintended side-effects.

Note: `ValueError: Invalid model type. Expected SQLAlchemy DeclarativeBase or SQLModel, but got DeclarativeAttributeIntercept. Please ensure you're using a valid SQLAlchemy or SQLModel model.`

2024-06-28 16:17 UTC, kdcokenny commented
Also, I would like to suggest adding Makefile to simplify testing, linting, and formatting. I find a universal `make format`, `make lint`, `make test` to be easier to remember than their counterparts like `ruff check --fix`. Also, isort for import sorting might be a nice addition, not my lib though so do whatever you prefer!

2024-06-28 18:05 UTC, JakNowy commented
> Also, I would like to suggest adding Makefile to simplify testing, linting, and formatting. I find a universal `make format`, `make lint`, `make test` to be easier to remember than their counterparts like `ruff check --fix`.

I am highly against this, make introduces yet another layer of abstraction. We should stick to poetry and docker compose exec's whenever possible. What you might be interrested in is:
```
poetry run ruff check fastcrud
```

2024-06-29 23:40 UTC, igorbenav commented
> So I did make the `Any` changes above. I also tried adding in run-time validation with:
> 
> ```python
> ...
>     if not isinstance(model, DeclarativeBase):
>         try:
>             from sqlmodel.main import SQLModel, SQLModelMetaclass
>             if not isinstance(model, Union[SQLModel, SQLModelMetaclass]):
>                 raise ValueError(
>                     f"Invalid model type. Expected SQLAlchemy DeclarativeBase or SQLModel, "
>                     f"but got {type(model).__name__}. "
>                     f"Please ensure you're using a valid SQLAlchemy or SQLModel model."
>                 )
>         except ImportError:
>             raise ImportError(
>                 f"Invalid model type. Expected SQLAlchemy DeclarativeBase, but got {type(model).__name__}. "
>                 f"To use SQLModel, ensure you have installed the 'sqlmodel' package. "
>                 f"You can install it using 'pip install sqlmodel' or 'poetry add sqlmodel'."
>             )
> ```
> 
> However, it kept failing tests with random model types which I could manually check for, but am not familiar enough with these libraries to confidently say that would not lead to massive unintended side-effects.
> 
> Note: `ValueError: Invalid model type. Expected SQLAlchemy DeclarativeBase or SQLModel, but got DeclarativeAttributeIntercept. Please ensure you're using a valid SQLAlchemy or SQLModel model.`

Something like this would be good indeed. I think we could revisit in the future, but for now it looks good to me. Is it actually working with the [example in the issue](https://github.com/igorbenav/fastcrud/issues/58#issue-2259676023)?

2024-06-29 23:43 UTC, igorbenav commented
> Also, isort for import sorting might be a nice addition, not my lib though so do whatever you prefer!

Ruff does this, `ruff check --select I --fix`. A github action to do this would be nice

2024-06-29 23:43 UTC, igorbenav approved these changes

2024-06-29 23:48 UTC, igorbenav commented
> > Also, I would like to suggest adding Makefile to simplify testing, linting, and formatting. I find a universal `make format`, `make lint`, `make test` to be easier to remember than their counterparts like `ruff check --fix`.
> 
> I am highly against this. Make introduces yet another layer of abstraction. We should stick to poetry and docker compose exec's whenever possible. What you might be interrested in is:
> 
> ```
> poetry run ruff check fastcrud
> ```

I agree. The commands are in [contributing.md](https://github.com/igorbenav/fastcrud/blob/main/CONTRIBUTING.md), we could add them to readme as well to make it easier.

2024-07-02 00:30 UTC, kdcokenny commented
> > So I did make the `Any` changes above. I also tried adding in run-time validation with:
> > ```python
> > ...
> >     if not isinstance(model, DeclarativeBase):
> >         try:
> >             from sqlmodel.main import SQLModel, SQLModelMetaclass
> >             if not isinstance(model, Union[SQLModel, SQLModelMetaclass]):
> >                 raise ValueError(
> >                     f"Invalid model type. Expected SQLAlchemy DeclarativeBase or SQLModel, "
> >                     f"but got {type(model).__name__}. "
> >                     f"Please ensure you're using a valid SQLAlchemy or SQLModel model."
> >                 )
> >         except ImportError:
> >             raise ImportError(
> >                 f"Invalid model type. Expected SQLAlchemy DeclarativeBase, but got {type(model).__name__}. "
> >                 f"To use SQLModel, ensure you have installed the 'sqlmodel' package. "
> >                 f"You can install it using 'pip install sqlmodel' or 'poetry add sqlmodel'."
> >             )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, it kept failing tests with random model types which I could manually check for, but am not familiar enough with these libraries to confidently say that would not lead to massive unintended side-effects.
> > Note: `ValueError: Invalid model type. Expected SQLAlchemy DeclarativeBase or SQLModel, but got DeclarativeAttributeIntercept. Please ensure you're using a valid SQLAlchemy or SQLModel model.`
> 
> Something like this would be good indeed. I think we could revisit in the future, but for now it looks good to me. Is it actually working with the [example in the issue](https://github.com/igorbenav/fastcrud/issues/58#issue-2259676023)?

Yes, the issues don't appear for me with my changes with his example code.

2024-07-03 12:56 UTC, merged