Select method changes and docs
igorbenav/fastcrud pull request #32
Opened 2024-03-21 17:51 UTC by igorbenav

# Pull Request Template for FastCRUD

## Description
This is essentially a bug fix + docs for #28 by @dubusster 

## Changes
- bug fix
- docstring enhanced
- docs added both in `usage` and `advanced`

## Tests
- more tests
- tests reformatted to multiple functions

## Detailed Bug Fix

In select, checking whether `sort_columns` are provided were written as follows:
```python
if "sort_columns":
           stmt = self._apply_sorting(stmt, sort_columns, sort_orders)
```

Which was fixed to:
```python
if sort_columns:
           stmt = self._apply_sorting(stmt, sort_columns, sort_orders)
```

2024-03-21 17:52 UTC, igorbenav commented
Hey, @dubusster, do you want to take a look?

2024-03-21 18:50 UTC, dubusster commented
Oups, thanks for the fix and the additional tests @igorbenav!

2024-03-21 18:54 UTC, dubusster commented
I'll have a look tomorrow to maybe add some more detailed tests

2024-03-22 08:21 UTC, dubusster approved these changes

2024-03-22 08:33 UTC, dubusster requested changes
I also missed some typing in fast_crud.py

2024-03-22 08:33 UTC, dubusster commented on fastcrud/crud/fast_crud.py
>      ) -> Selectable:
I also missed some typing here : this should be of type `Select`, imported from `from sqlalchemy.sql.selectable import Select`

2024-03-23 00:54 UTC, merged